language: android

android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.2
    - android-23
    - extra-android-m2repository
    - extra-android-support
  licenses:
    - android-sdk-license-5be876d5

jdk:
  - oraclejdk8
  - oraclejdk7

script:
  - echo "Travis branch is $TRAVIS_BRANCH"
  - android list sdk --no-ui --all --extended | grep -E '^id:' | awk -F '"' '{$1=""; print $2}
  - ./gradlew clean check
  
branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.m2