language: android

android:
  components:
    - android-23
    - build-tools-23.0.2
    - extra-android-support
    - extra-android-m2repository    

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk8

script:
  # - android list sdk --no-ui --all --extended # Displays all components supported in travis
  - ./gradlew clean check
  
branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle