language: android

android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.2
    - android-23
    - extra-android-m2repository
    - extra-android-support
    - add-on
  licenses:
    - android-sdk-license-5be876d5

jdk:
  - oraclejdk8
  - oraclejdk7

script:
  # - android list sdk --no-ui --all --extended # Displays all components supported in travis
  - echo "Home is $HOME"
  - ./gradlew clean check
  
branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle