language: android

android:
  components:
    - android-23
	- platform-tools-23.1
    - build-tools-23.0.1
    - extra-android-support
    - extra-android-m2repository    

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

script:
  - android list sdk --no-ui --all --extended # Displays all components supported in travis
  - "echo Home is $HOME"
  - ./gradlew clean check
  
after_failure:
  - "cat $HOME/build/JaySoyer/Advanced-Adapters/app/build/outputs/lint-results.xml"
  
branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle